version: "3.8"

# Deployable Collector Host containers

services:
  imaprelay:
    image: "imaprelay:latest"
    build:
      dockerfile: "./docker/Dockerfile"
      context: "./"
    environment:
      - "IMAP_HOSTNAME=${IMAP_HOSTNAME:-localhost}"
      - "IMAP_USERNAME=${IMAP_USERNAME}:-"
      - "IMAP_PASSWORD=${IMAP_PASSWORD}:-"
      - "SMTP_HOSTNAME=${SMTP_HOSTNAME}:-"
      - "SMTP_USERNAME=${SMTP_USERNAME}:-"
      - "SMTP_PASSWORD=${SMTP_PASSWORD}:-"
      - "SMTP_SSL=${SMTP_SSL}:-false"
      - "SMTP_STARTTLS=${SMTP_STARTTLS}:-false"
      - "RELAY_TO=${RELAY_TO}:-nobody@localhost"
      - "MESSAGE_SOURCE=${MESSAGE_SOURCE}:-"
      - "MESSAGE_DESTINATION=${MESSAGE_DESTINATION}:-"
      - "POLLING_INTERVAL=${POLLING_INTERVAL}:-"
